import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/components/Home/Navbar/ResponsiveNav";
import { Bebas_Neue } from "next/font/google";
import { Oswald } from 'next/font/google';

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['500', '700'], // We load the weights needed for the design
  variable: '--font-oswald', // Optional: if you want to use it in tailwind config later
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bebas",
});

const font = Inter({
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Midhu's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased bg-linear-to-b from-[#376d4a] to-[#1f563a]
`}
      >
        <ResponsiveNav />
        {children}
      </body>
    </html>
  );
}
